### ISSUE TITLE
Failed to activate the atom-image-paste package

### ISSUE THREAD

**Issue by AnetteMM** [rustielin/atom-image-paste#2]
Thank you for taking a look!

1. Copied image to clipboard
2. Chose packages>atom-image-paste>Paste image

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: DESKTOP-8RDUPPT
**Thrown From**: [atom-image-paste](https://github.com/rustielin/atom-image-paste) package 1.2.0

### Stack Trace

Failed to activate the atom-image-paste package

```
At Cannot find module 'shelljs'

Error: Cannot find module 'shelljs'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.33.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:145974)
    at /packages/atom-image-paste/lib/atom-image-paste.coffee:2:9)
    at /packages/atom-image-paste/lib/atom-image-paste.coffee:1:1)
    at /packages/atom-image-paste/lib/atom-image-paste.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:1:639369)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3041061)
    at Package.activateNow (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3029195)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:1717)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1190759)
    at Emitter.emit (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1192200)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:349666)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:348509)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:1:669041)
    at EventEmitter.t (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:1:676425)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -5:58.7.0 markdown:image (input.hidden-input)
     -5:56.2.0 core:move-down (input.hidden-input)
     -5:53.5.0 core:move-left (input.hidden-input)
     -5:52.1.0 core:backspace (input.hidden-input)
     -5:51.3.0 core:move-left (input.hidden-input)
     -5:50.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -5:50.8.0 editor:newline (input.hidden-input)
     -5:47.7.0 core:delete (input.hidden-input)
 85x -5:17.7.0 core:move-down (div.panels-item)
 69x -2:27.7.0 core:move-up (div.package-detail.panels-item)
 21x -1:53.3.0 core:move-down (div.package-detail.panels-item)
 20x -1:39 core:move-up (div.package-detail.panels-item)
undefined -1:24.6.0 core:move-down (div.panels-item)
  3x -1:06.8.0 core:move-up (div.panels-item)
     -0:37.1.0 core:paste (input.hidden-input)
     -0:23.3.0 atom-image-paste:toggle (webview.markdown-preview-plus.native-key-bindings)
```

### Non-Core Packages

```
asciidoc-image-helper 1.0.1 
atom-clock 0.1.16 
atom-image-paste 1.2.0 
atom-journal 1.3.1 
click-link 1.0.11 
document-outline 2.1.2 
file-icons 2.1.27 
find-scroll-marker 0.1.3 
go-to-file 0.2.0 
image-copipe 0.3.1 
inline-markdown-images 1.15.0 
journal 0.1.1 
language-markdown 0.28.0 
line-breaker 0.4.1 
lint-scroll-marker 0.3.0 
markdown-folding 0.3.1 
markdown-image-assistant 0.2.1 
markdown-image-helper 1.0.4 
markdown-image-insert 1.5.2 
markdown-image-insertion 0.2.1 
markdown-image-paste 2.5.2 
markdown-mindmap 0.6.1 
markdown-preview-opener 0.1.1 
markdown-preview-plus 3.7.1 
markdown-writer 2.11.3 
mdattachment 0.3.0 
multiline-tab 0.2.1 
pdf-view 0.71.0 
preview 0.19.0 
preview-plus 1.2.7 
scroll-marker 0.3.0 
secondmemory 0.2.0 
show-first-line-on-tab 0.3.7 
svg-preview 0.14.0 
tomatimer 1.2.3 
tool-bar 1.1.11 
tool-bar-markdown-writer 0.5.0 
tree-view-open-files-updated 1.1.0 
wordcount 3.0.0 
```

**Comment by MikeStL87** [comment]
i had this same problem but then googled online and did "npm install shelljs" and it went away
